SUBSIDIARY_NAME_MAP = {
    "AGROBUSINESS INTERNATIONAL PERU SAC": "AGROBUSINESS INTERNATIONAL PERU SAC",
    "ALZA PERU GROUP SAC": "ALZA PERU GROUP SAC",
    "ALZA PERU PACKING S.A.C.": "ALZA PERU PACKING SAC",
    "APG": "APG",
    "BERRIES": "BERRIES",
    "BIG BERRIES S.A.C.": "BIG BERRIES SAC",
    "CANYON BERRIES S.A.C.": "CANYON BERRIES SAC",
    "EXCELLENCE FRUIT S.A.C.": "EXCELLENCE FRUIT SAC",
    "GAP BERRIES S.A.C": "GAP BERRIES SAC",
    "GOLDEN BERRIES S.A.C.": "GOLDEN BERRIES SAC",
    "INMOBILIARIA SAN JUAN SA": "INMOBILIARIA SAN JUAN SA",
    "INVERSIONES QUELEN PERU SAC": "INVERSIONES QUELEN PERU SAC",
    "QBERRIES S.A.C": "QBERRIES SAC",
    "TARA FARM S.A.C.": "TARA FARM SAC",
    "TECNOLOGIAS ORGANICAS TAKAMATSU SAC": "TECNOLOGIAS ORGANICAS TAKAMATSU SAC",
    "360 SMART AGRO SAC": "360 SMART AGRO SAC",
}

UBICACION_REPLACEMENTS = {
    "SAN JOSE": "SAN JOSE I",
}

CLASS_ABBREVIATION_MAP = {
    "ADMPERS": "ADMINISTRACION DE PERSONAL",
    "GHSSOMA": "SSOMA",
    "BIENEST": "BIENESTAR SOCIAL",
    "COSECHA": "COSECHA",
    "MANTENC": "MANTENCION",
}

CODE_CORRECTIONS = {
    "O014": "O0014",
    "C001": "C0001",
    "O006": "O0006",
    "O004": "O0004",
    "O005": "O0005",
    "O009": "O0009",
    "O012": "O0012",
}
