# Generated by Django 5.2.8 on 2026-04-07 15:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='Tamaño en bytes')),
                ('planilla_type', models.CharField(choices=[('empleados', 'Empleados'), ('obreros', 'Obreros'), ('vida_ley', 'Vida Ley')], max_length=20)),
                ('subsidiary_name', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(choices=[('preview', 'Vista Previa'), ('success', 'Exitoso'), ('error', 'Error'), ('validation_error', 'Error de Validación')], default='preview', max_length=20)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('total_debit', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('total_credit', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('netsuite_payload', models.JSONField(blank=True, null=True)),
                ('netsuite_response', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Carga',
                'verbose_name_plural': 'Historial de Cargas',
                'ordering': ['-create'],
            },
        ),
    ]
