# Generated by Django 5.2.8 on 2026-04-07 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yw_oracle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadhistory',
            name='status',
            field=models.CharField(choices=[('preview', 'Vista Previa'), ('sending', 'Enviando a NetSuite'), ('success', 'Exitoso'), ('error', 'Error'), ('validation_error', 'Error de Validación')], default='preview', max_length=20),
        ),
    ]
