# Generated by Django 5.2.8 on 2026-04-08 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yw_oracle', '0002_alter_uploadhistory_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadhistory',
            name='transformed_columns',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadhistory',
            name='transformed_data',
            field=models.JSONField(blank=True, help_text='DataFrame transformado completo para descarga', null=True),
        ),
    ]
